CREATE DATABASE IF NOT EXISTS `mini-stile`;

CREATE TABLE users (
  user_id INTEGER NOT NULL AUTO_INCREMENT, 
  username VARCHAR(255)  NOT NULL, 
  email VARCHAR(255)  NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`)
);


ALTER TABLE users ADD CONSTRAINT MIN_USERNAME CHECK (CHAR_LENGTH(username) >= 1);
ALTER TABLE users ADD CONSTRAINT MIN_EMAIL CHECK (CHAR_LENGTH(email) >= 1);
ALTER TABLE users ADD CONSTRAINT MIN_PASSWORD CHECK (CHAR_LENGTH(password) >= 1)